name: Version

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    paths:
    - apparmor.txt
    - '*.json'

env:
  PYTHON_VERSION: "3.7"
  BRANCH_CONDITION: "refs/heads/master"

jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout the repository
#      uses: actions/checkout@v2
# 
#    - name: Lint with JQ
#      uses: home-assistant/actions/helpers/jq@master

  upload:
    name: Upload
    #needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Flush CloudFlare cache
      run: |

        curl --silent --show-error --fail -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_TOKEN }}"\
            -H "Content-Type: application/json" \
            --data '{"files": ["https:\/\/www.halfdecent.io\/cat.jpg","https:\/\/www.halfdecent.io\/dog.jpg"]}'
